/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'whisperdesk-screencapturekit.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./whisperdesk-screencapturekit.android-arm64.node')
          } else {
            nativeBinding = require('whisperdesk-screencapturekit-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'whisperdesk-screencapturekit.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./whisperdesk-screencapturekit.android-arm-eabi.node')
          } else {
            nativeBinding = require('whisperdesk-screencapturekit-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'whisperdesk-screencapturekit.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./whisperdesk-screencapturekit.win32-x64-msvc.node')
          } else {
            nativeBinding = require('whisperdesk-screencapturekit-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'whisperdesk-screencapturekit.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./whisperdesk-screencapturekit.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('whisperdesk-screencapturekit-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'whisperdesk-screencapturekit.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./whisperdesk-screencapturekit.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('whisperdesk-screencapturekit-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'whisperdesk-screencapturekit.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./whisperdesk-screencapturekit.darwin-universal.node')
      } else {
        nativeBinding = require('whisperdesk-screencapturekit-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'whisperdesk-screencapturekit.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./whisperdesk-screencapturekit.darwin-x64.node')
          } else {
            nativeBinding = require('whisperdesk-screencapturekit-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'whisperdesk-screencapturekit.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./whisperdesk-screencapturekit.darwin-arm64.node')
          } else {
            nativeBinding = require('whisperdesk-screencapturekit-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'whisperdesk-screencapturekit.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./whisperdesk-screencapturekit.freebsd-x64.node')
      } else {
        nativeBinding = require('whisperdesk-screencapturekit-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'whisperdesk-screencapturekit.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./whisperdesk-screencapturekit.linux-x64-musl.node')
            } else {
              nativeBinding = require('whisperdesk-screencapturekit-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'whisperdesk-screencapturekit.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./whisperdesk-screencapturekit.linux-x64-gnu.node')
            } else {
              nativeBinding = require('whisperdesk-screencapturekit-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'whisperdesk-screencapturekit.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./whisperdesk-screencapturekit.linux-arm64-musl.node')
            } else {
              nativeBinding = require('whisperdesk-screencapturekit-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'whisperdesk-screencapturekit.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./whisperdesk-screencapturekit.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('whisperdesk-screencapturekit-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'whisperdesk-screencapturekit.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./whisperdesk-screencapturekit.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('whisperdesk-screencapturekit-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'whisperdesk-screencapturekit.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./whisperdesk-screencapturekit.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('whisperdesk-screencapturekit-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'whisperdesk-screencapturekit.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./whisperdesk-screencapturekit.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('whisperdesk-screencapturekit-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'whisperdesk-screencapturekit.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./whisperdesk-screencapturekit.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('whisperdesk-screencapturekit-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'whisperdesk-screencapturekit.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./whisperdesk-screencapturekit.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('whisperdesk-screencapturekit-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { ContentManager, RealContentFilter, RealStreamManager, K_CV_PIXEL_FORMAT_TYPE_32_BGRA, K_CG_COLOR_SPACE_SRGB, K_CG_COLOR_SPACE_DISPLAY_P3, kCVPixelFormatType_32BGRA, kCGColorSpaceSRGB, ShareableContent, ScreenCaptureKitRecorder, initScreencapturekit, getVersion, checkScreenRecordingPermission, requestScreenRecordingPermission, checkMacosVersion, testPermissionsAndApi, testScreencapturekitWithTimeout, testPhase2Implementation, AudioManager } = nativeBinding

module.exports.ContentManager = ContentManager
module.exports.RealContentFilter = RealContentFilter
module.exports.RealStreamManager = RealStreamManager
module.exports.K_CV_PIXEL_FORMAT_TYPE_32_BGRA = K_CV_PIXEL_FORMAT_TYPE_32_BGRA
module.exports.K_CG_COLOR_SPACE_SRGB = K_CG_COLOR_SPACE_SRGB
module.exports.K_CG_COLOR_SPACE_DISPLAY_P3 = K_CG_COLOR_SPACE_DISPLAY_P3
module.exports.kCVPixelFormatType_32BGRA = kCVPixelFormatType_32BGRA
module.exports.kCGColorSpaceSRGB = kCGColorSpaceSRGB
module.exports.ShareableContent = ShareableContent
module.exports.ScreenCaptureKitRecorder = ScreenCaptureKitRecorder
module.exports.initScreencapturekit = initScreencapturekit
module.exports.getVersion = getVersion
module.exports.checkScreenRecordingPermission = checkScreenRecordingPermission
module.exports.requestScreenRecordingPermission = requestScreenRecordingPermission
module.exports.checkMacosVersion = checkMacosVersion
module.exports.testPermissionsAndApi = testPermissionsAndApi
module.exports.testScreencapturekitWithTimeout = testScreencapturekitWithTimeout
module.exports.testPhase2Implementation = testPhase2Implementation
module.exports.AudioManager = AudioManager
